leftnav:
- identifier: bf471999-c54c-4c8d-a26b-5facb2df3b5f
  name: Quantum Information Science I, Part 1
  pageRef: /external-resources/quantum-information-science-i-part-1_bf471999-c54c-4c8d-a26b-5facb2df3b5f
  weight: 10
- identifier: de7a94ba-40ec-4edb-8484-a0efb4ad985d
  name: Quantum Information Science I, Part 2
  pageRef: /external-resources/quantum-information-science-i-part-2_de7a94ba-40ec-4edb-8484-a0efb4ad985d
  weight: 20
- identifier: 27d9a5c7-85a7-4bb8-98b1-61321a770e2e
  name: Quantum Information Science I, Part 3
  pageRef: /external-resources/quantum-information-science-i-part-3_27d9a5c7-85a7-4bb8-98b1-61321a770e2e
  weight: 30
